# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 12:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=20)),
                ('email_id', models.CharField(default='', max_length=30)),
                ('password', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('email_id', models.CharField(default='', max_length=30)),
                ('password', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='feedback',
            name='course',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='feeder.Course'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='email_id',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='password',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='username',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(to='feeder.Course'),
        ),
    ]
