# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0004_auto_20161027_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='email_id',
        ),
        migrations.AddField(
            model_name='instructor',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
