# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0005_auto_20161029_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='course',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
