# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 21:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0006_auto_20161029_2230'),
    ]

    operations = [
        migrations.CreateModel(
            name='rating_question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(default='', max_length=100)),
                ('rate', models.IntegerField(default=2)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feeder.Feedback')),
            ],
        ),
    ]
