# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0007_rating_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.CharField(choices=[('Aut', 'Autumn'), ('Spr', 'Spring'), ('Sum', 'Summer')], max_length=2),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback_name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
