# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 00:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0009_auto_20161031_0011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='deadline',
        ),
        migrations.AddField(
            model_name='feedback',
            name='deadline_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='feedback',
            name='deadline_time',
            field=models.TimeField(default='23:59'),
        ),
    ]
