# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0010_auto_20161031_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.CharField(choices=[('Autumn', 'Autumn'), ('Spring', 'Spring'), ('Summer', 'Summer')], max_length=6),
        ),
    ]
