# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0011_auto_20161031_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='rollnumber',
            field=models.CharField(default='', max_length=9),
        ),
    ]
