# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0012_student_rollnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='loggedin',
            field=models.BooleanField(default=False),
        ),
    ]
