# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0014_auto_20161031_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='email_id',
            field=models.EmailField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='email_id',
            field=models.EmailField(default='', max_length=30),
        ),
    ]
