# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 19:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0015_auto_20161031_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deadline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_name', models.CharField(default='', max_length=20)),
                ('deadline_date', models.DateField(default=datetime.date.today)),
                ('deadline_time', models.TimeField(default='23:59')),
                ('course', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='feeder.Course')),
            ],
        ),
    ]
