# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0016_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='instructor',
        ),
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.ManyToManyField(to='feeder.Instructor'),
        ),
    ]
