# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 00:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0017_auto_20161031_2252'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='rating_question',
            new_name='RatingQuestion',
        ),
    ]
