# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 01:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0018_auto_20161101_0057'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectiveQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(default='', max_length=100)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feeder.Feedback')),
            ],
        ),
        migrations.RemoveField(
            model_name='ratingquestion',
            name='rate',
        ),
    ]
