# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-04 14:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0020_remove_feedback_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_rated', models.IntegerField(default=3)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feeder.RatingQuestion')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feeder.Student')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectiveAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_rated', models.CharField(default='', max_length=100)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feeder.SubjectiveQuestion')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feeder.Student')),
            ],
        ),
    ]
