# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-05 01:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0021_ratinganswer_subjectiveanswer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjectiveanswer',
            old_name='answer_rated',
            new_name='answer',
        ),
    ]
