# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-05 01:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0022_auto_20161105_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectiveanswer',
            name='answer',
            field=models.CharField(default='', max_length=150),
        ),
    ]
